/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tanabata;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;

/**
 *
 * @author User
 */
public class ParamChooser extends javax.swing.JFrame {

    public Integer clipNumber = 1;
    public Twitter twitter = new TwitterFactory().getInstance();
    
    /**
     * Creates new form ParamChooser
     */
    public ParamChooser() {
        initComponents();
        this.lstClipsModel = new DefaultListModel();
        this.lstClips.setModel(this.lstClipsModel);
        this.lstUploaderClipsModel = new DefaultListModel();
        this.lstUploaderClips.setModel(this.lstUploaderClipsModel);
        this.lstSharerLinksModel = new DefaultListModel();
        this.lstSharerLinks.setModel(this.lstSharerLinksModel);
        
        String consumerKey = "z4tD7RW6JvmHg1iQ91hdSw";
        String consumerSecret = "TsCQQR7OJveTYg9lYQIxU8psMVrCwyQC3mtphsM";
        this.twitter.setOAuthConsumer(consumerKey, consumerSecret);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnPlayVideo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstClips = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        txtStream = new javax.swing.JTextField();
        btnAddClip = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtFromHour = new javax.swing.JTextField();
        txtFromMinute = new javax.swing.JTextField();
        txtFromSecond = new javax.swing.JTextField();
        txtToSecond = new javax.swing.JTextField();
        txtToMinute = new javax.swing.JTextField();
        txtToHour = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPathClips = new javax.swing.JTextField();
        btnClip = new javax.swing.JButton();
        lblThumb = new javax.swing.JLabel();
        btnRecordStop = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtClipLog = new javax.swing.JTextArea();
        btnPlaySelected = new javax.swing.JButton();
        btnRecordNext = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUploaderClips = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtUploaderLog = new javax.swing.JTextArea();
        btnUploaderYoutube = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtUploaderTitle = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtUploaderDescription = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtUploaderTags = new javax.swing.JTextField();
        btnUploaderResetYoutubeCredentials = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSharerText = new javax.swing.JTextArea();
        btnSharerTwitter = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstSharerLinks = new javax.swing.JList();
        btnSharerCopyLink = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtSharerLog = new javax.swing.JTextArea();
        btnSharerFacebook = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        scrollpane = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtClipLimit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPercentage1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnShuffle = new javax.swing.JButton();
        txtMaxDuration = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSearchTerm = new javax.swing.JTextField();
        txtPath = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClipLength = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCommentSearch = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCommentVideoLimit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCommentCommentLimit = new javax.swing.JTextField();
        btnCommentGo = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtCommentLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tanabata");

        btnPlayVideo.setText("Record");
        btnPlayVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayVideoActionPerformed(evt);
            }
        });

        lstClips.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstClips);

        jLabel7.setText("Stream");

        txtStream.setText("rtmp://live4.stweb.tv/fans/live1");
        txtStream.setToolTipText("");

        btnAddClip.setText("Add");
        btnAddClip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClipActionPerformed(evt);
            }
        });

        jLabel8.setText("From");

        txtFromHour.setText("00");

        txtFromMinute.setText("00");

        txtFromSecond.setText("00");

        txtToSecond.setText("00");

        txtToMinute.setText("00");

        txtToHour.setText("00");

        jLabel9.setText("To");
        jLabel9.setToolTipText("");

        jLabel10.setText("Path");

        txtPathClips.setText("c:\\programas\\grabaciones\\");
            txtPathClips.setToolTipText("");

            btnClip.setText("Clip!");
            btnClip.setToolTipText("");
            btnClip.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnClipActionPerformed(evt);
                }
            });

            btnRecordStop.setText("Stop");
            btnRecordStop.setEnabled(false);
            btnRecordStop.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnRecordStopActionPerformed(evt);
                }
            });

            txtClipLog.setColumns(20);
            txtClipLog.setRows(5);
            jScrollPane2.setViewportView(txtClipLog);

            btnPlaySelected.setText("Play selected");
            btnPlaySelected.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPlaySelectedActionPerformed(evt);
                }
            });

            btnRecordNext.setText("Next");
            btnRecordNext.setEnabled(false);
            btnRecordNext.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnRecordNextActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblThumb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnAddClip)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFromHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFromMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFromSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtToHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtToMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtToSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnClip)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jScrollPane2)
                                    .addContainerGap())))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtStream, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPlayVideo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRecordStop)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRecordNext))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPathClips, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnPlaySelected))
                            .addGap(0, 28, Short.MAX_VALUE))))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPlayVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRecordStop, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRecordNext))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtPathClips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addComponent(lblThumb, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2))
                    .addGap(1, 1, 1)
                    .addComponent(btnPlaySelected)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddClip)
                        .addComponent(jLabel8)
                        .addComponent(txtFromHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFromMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFromSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtToHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtToMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtToSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClip))
                    .addContainerGap(119, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Clipper", jPanel2);

            lstUploaderClips.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            jScrollPane3.setViewportView(lstUploaderClips);

            txtUploaderLog.setColumns(20);
            txtUploaderLog.setRows(5);
            jScrollPane4.setViewportView(txtUploaderLog);

            btnUploaderYoutube.setText("Upload to Youtube");
            btnUploaderYoutube.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnUploaderYoutubeActionPerformed(evt);
                }
            });

            jLabel11.setText("Title");

            jLabel12.setText("Description");

            txtUploaderDescription.setColumns(20);
            txtUploaderDescription.setRows(5);
            jScrollPane5.setViewportView(txtUploaderDescription);

            jLabel13.setText("Tags (a,b)");

            btnUploaderResetYoutubeCredentials.setText("Reset YT Credentials");
            btnUploaderResetYoutubeCredentials.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnUploaderResetYoutubeCredentialsActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnUploaderYoutube)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnUploaderResetYoutubeCredentials)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUploaderTags)
                                .addComponent(txtUploaderTitle)
                                .addComponent(jScrollPane5))))
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtUploaderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtUploaderTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUploaderYoutube)
                        .addComponent(btnUploaderResetYoutubeCredentials))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("Uploader", jPanel3);

            jLabel14.setText("Text");

            txtSharerText.setColumns(20);
            txtSharerText.setRows(5);
            jScrollPane6.setViewportView(txtSharerText);

            btnSharerTwitter.setText("Share to Twitter");
            btnSharerTwitter.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSharerTwitterActionPerformed(evt);
                }
            });

            lstSharerLinks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            jScrollPane7.setViewportView(lstSharerLinks);

            btnSharerCopyLink.setText("Copy link into text");
            btnSharerCopyLink.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSharerCopyLinkActionPerformed(evt);
                }
            });

            txtSharerLog.setColumns(20);
            txtSharerLog.setRows(5);
            jScrollPane8.setViewportView(txtSharerLog);

            btnSharerFacebook.setText("Share to Facebook (url only)");
            btnSharerFacebook.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSharerFacebookActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane8)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSharerCopyLink, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(btnSharerTwitter)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSharerFacebook)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSharerCopyLink)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSharerTwitter)
                        .addComponent(btnSharerFacebook))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("Sharer", jPanel4);

            txtLog.setColumns(20);
            txtLog.setRows(5);
            scrollpane.setViewportView(txtLog);

            jLabel6.setText("Path");

            txtClipLimit.setText("10");
            txtClipLimit.setToolTipText("");
            txtClipLimit.setMinimumSize(new java.awt.Dimension(100, 20));

            jLabel5.setText("Max duration");

            jLabel1.setText("Search term");

            txtPercentage1.setText("50");
            txtPercentage1.setToolTipText("");
            txtPercentage1.setMinimumSize(new java.awt.Dimension(100, 20));

            jLabel3.setText("Clip length");

            btnShuffle.setText("Shuffle!");
            btnShuffle.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnShuffleActionPerformed(evt);
                }
            });

            txtMaxDuration.setText("400");

            jLabel2.setText("Percentage");

            txtSearchTerm.setText("science");
            txtSearchTerm.setToolTipText("");
            txtSearchTerm.setMinimumSize(new java.awt.Dimension(100, 20));

            txtPath.setText("c:\\programas\\grabaciones");

            jLabel4.setText("Clip limit");

            txtClipLength.setText("5");
            txtClipLength.setToolTipText("");
            txtClipLength.setMinimumSize(new java.awt.Dimension(100, 20));

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(scrollpane)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtClipLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShuffle))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtSearchTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5))
                                        .addComponent(txtClipLength, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtPercentage1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel6)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMaxDuration)
                                        .addComponent(txtPath, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(109, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtSearchTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtMaxDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPercentage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtClipLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtClipLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnShuffle))
                    .addGap(18, 18, 18)
                    .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("Shuffler", jPanel1);

            jLabel15.setText("Search");

            txtCommentSearch.setText("miley cyrus");

            jLabel16.setText("Videos #");

            txtCommentVideoLimit.setText("5");

            jLabel17.setText("Comments #");

            txtCommentCommentLimit.setText("5");

            btnCommentGo.setText("Go");
            btnCommentGo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCommentGoActionPerformed(evt);
                }
            });

            txtCommentLog.setColumns(20);
            txtCommentLog.setRows(5);
            jScrollPane9.setViewportView(txtCommentLog);

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane9)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCommentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCommentVideoLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCommentCommentLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                            .addComponent(btnCommentGo)))
                    .addContainerGap())
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtCommentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtCommentVideoLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(txtCommentCommentLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCommentGo))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("Commentfind", jPanel5);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnShuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShuffleActionPerformed
        // TODO add your handling code here:
        this.btnShuffle.setEnabled(false);
        
        Integer cliplength = Integer.parseInt(this.txtClipLength.getText());
        Integer percentage = Integer.parseInt(this.txtPercentage1.getText());
        String searchterm = this.txtSearchTerm.getText();
        Integer cliplimit = Integer.parseInt(this.txtClipLimit.getText());
        Integer maxduration = Integer.parseInt(this.txtMaxDuration.getText());
        String path = this.txtPath.getText();
        
        YoutubeFinder yf = new YoutubeFinder(this.txtLog);
        List<Video> videos = yf.findIds(searchterm, cliplimit, maxduration);
            
        VideoStreamFiller vsf = new VideoStreamFiller(this.txtLog);
        videos = vsf.fillVideos(videos, path);
        
        ClipDownloader cd = new ClipDownloader(this.txtLog);
        cd.downloadClips(videos, percentage, cliplength, path);
        
        ClipCombiner cc = new ClipCombiner(this.txtLog);
        cc.combineClips(videos, path);
        
        this.btnShuffle.setEnabled(true);
    }//GEN-LAST:event_btnShuffleActionPerformed

    private void btnPlayVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayVideoActionPerformed
        // TODO add your handling code here:
        String stream = this.txtStream.getText();
        String path = this.txtPathClips.getText();
        this.recordThread = new StreamRecorder(stream, path, this.clipNumber, this.lstClipsModel, this.txtClipLog);
        this.recordThread.start();
        this.clipNumber++;
        this.btnPlayVideo.setEnabled(false);
        this.btnRecordStop.setEnabled(true);
        this.btnRecordNext.setEnabled(true);
    }//GEN-LAST:event_btnPlayVideoActionPerformed

    private void btnAddClipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClipActionPerformed
        // TODO add your handling code here:
        String clipName = "record" + this.clipNumber;
        this.lstClipsModel.addElement(clipName);
        this.txtClipLog.append("Force added " + clipName + "\n");
        this.clipNumber++;
        /*
        Image img = null;
        try {
            
            img = ImageIO.read(new File("c:\\programas\\grabaciones\\record1_thumb.jpg"));
            
            Image scaledImage = img.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            BufferedImage imageBuff = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
            Graphics g = imageBuff.createGraphics();
            g.drawImage(scaledImage, 0, 0, new Color(0,0,0), null);
            g.dispose();
            
            ImageIcon icon = new ImageIcon(scaledImage);
            
            lblThumb.setIcon(icon);
        } catch (IOException e) {
        }*/
    }//GEN-LAST:event_btnAddClipActionPerformed

    private void btnClipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClipActionPerformed
        // TODO add your handling code here:
        String clipName = this.lstClips.getSelectedValue().toString();
        String from = this.txtFromHour.getText() + ":" +
                      this.txtFromMinute.getText() + ":" +
                      this.txtFromSecond.getText();
        String to = this.txtToHour.getText() + ":" +
                      this.txtToMinute.getText() + ":" +
                      this.txtToSecond.getText();
        
        String path = this.txtPathClips.getText();
        
        ClipCutter cc = new ClipCutter(this.txtClipLog);
        cc.cut(path, clipName, from, to, this.lstUploaderClipsModel);
    }//GEN-LAST:event_btnClipActionPerformed

    private void btnRecordStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordStopActionPerformed
        // TODO add your handling code here:
        this.recordThread.stoprec();
        this.btnPlayVideo.setEnabled(true);
        this.btnRecordStop.setEnabled(false);
        this.btnRecordNext.setEnabled(false);
    }//GEN-LAST:event_btnRecordStopActionPerformed

    private void btnPlaySelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySelectedActionPerformed
        // TODO add your handling code here:
        String clipName = this.lstClips.getSelectedValue().toString();
        String path = this.txtPathClips.getText();
        String filepath = path + clipName + ".flv";
        
        VideoPlayer vp = new VideoPlayer();
        vp.play(filepath);
    }//GEN-LAST:event_btnPlaySelectedActionPerformed

    private void btnRecordNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordNextActionPerformed
        // TODO add your handling code here:
        final StreamRecorder oldsr = this.recordThread;
        
        String stream = this.txtStream.getText();
        String path = this.txtPathClips.getText();
        this.recordThread = new StreamRecorder(stream, path, this.clipNumber, this.lstClipsModel, this.txtClipLog);
        this.recordThread.start();
        this.clipNumber++;
        
        new java.util.Timer().schedule(
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        oldsr.stoprec();
                    }
                },
                5000
        );
    }//GEN-LAST:event_btnRecordNextActionPerformed

    private void btnUploaderYoutubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploaderYoutubeActionPerformed
        // TODO add your handling code here:
        String title = this.txtUploaderTitle.getText();
        String description = this.txtUploaderDescription.getText();
        String[] tx = this.txtUploaderTags.getText().split(",");
        List<String> tags = new ArrayList<>();
        tags.addAll(Arrays.asList(tx));
        
        String filepath = this.lstUploaderClips.getSelectedValue().toString();
        
        YoutubeUpload.upload(filepath, title, description, tags, this.txtUploaderLog, this.lstSharerLinksModel);
    }//GEN-LAST:event_btnUploaderYoutubeActionPerformed

    private void btnSharerTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSharerTwitterActionPerformed
        try {
            // TODO add your handling code here:
            String text = this.txtSharerText.getText();
            
            if (this.twitter.getOAuthAccessToken() != null) {
                TwitterShare.share(text, this.twitter, this.txtSharerLog);
            }
        } catch (Exception ex) {
            TwitterShare.auth(this.twitter);
        }
    }//GEN-LAST:event_btnSharerTwitterActionPerformed

    private void btnSharerCopyLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSharerCopyLinkActionPerformed
        // TODO add your handling code here:
        String selected = this.lstSharerLinks.getSelectedValue().toString();
        this.txtSharerText.append(selected);
    }//GEN-LAST:event_btnSharerCopyLinkActionPerformed

    private void btnSharerFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSharerFacebookActionPerformed
        // TODO add your handling code here:
        String text = this.txtSharerText.getText();
        FacebookShare.share(text, this.txtSharerLog);
    }//GEN-LAST:event_btnSharerFacebookActionPerformed

    private void btnUploaderResetYoutubeCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploaderResetYoutubeCredentialsActionPerformed
        // TODO add your handling code here:
        if (Auth.revoke("uploadvideo")) {
            this.txtUploaderLog.append("Youtube upload credentials reset" + "\n");
        } else {
            this.txtUploaderLog.append("Reset credentials failed" + "\n");
        }
    }//GEN-LAST:event_btnUploaderResetYoutubeCredentialsActionPerformed

    private void btnCommentGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentGoActionPerformed
        // TODO add your handling code here:
        String search = this.txtCommentSearch.getText();
        Integer videolimit = Integer.parseInt(this.txtCommentVideoLimit.getText());
        Integer commentlimit = Integer.parseInt(this.txtCommentCommentLimit.getText());
        
        YoutubeCommentFinder ycf = new YoutubeCommentFinder();
        ycf.find(search, videolimit, commentlimit, this.txtCommentLog);
    }//GEN-LAST:event_btnCommentGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParamChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParamChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParamChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParamChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParamChooser().setVisible(true);
            }
        });
    }

    private DefaultListModel lstClipsModel;
    private DefaultListModel lstUploaderClipsModel;
    private DefaultListModel lstSharerLinksModel;
    private StreamRecorder recordThread;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClip;
    private javax.swing.JButton btnClip;
    private javax.swing.JButton btnCommentGo;
    private javax.swing.JButton btnPlaySelected;
    private javax.swing.JButton btnPlayVideo;
    private javax.swing.JButton btnRecordNext;
    private javax.swing.JButton btnRecordStop;
    private javax.swing.JButton btnSharerCopyLink;
    private javax.swing.JButton btnSharerFacebook;
    private javax.swing.JButton btnSharerTwitter;
    private javax.swing.JButton btnShuffle;
    private javax.swing.JButton btnUploaderResetYoutubeCredentials;
    private javax.swing.JButton btnUploaderYoutube;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblThumb;
    private javax.swing.JList lstClips;
    private javax.swing.JList lstSharerLinks;
    private javax.swing.JList lstUploaderClips;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JTextField txtClipLength;
    private javax.swing.JTextField txtClipLimit;
    private javax.swing.JTextArea txtClipLog;
    private javax.swing.JTextField txtCommentCommentLimit;
    private javax.swing.JTextArea txtCommentLog;
    private javax.swing.JTextField txtCommentSearch;
    private javax.swing.JTextField txtCommentVideoLimit;
    private javax.swing.JTextField txtFromHour;
    private javax.swing.JTextField txtFromMinute;
    private javax.swing.JTextField txtFromSecond;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtMaxDuration;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtPathClips;
    private javax.swing.JTextField txtPercentage1;
    private javax.swing.JTextField txtSearchTerm;
    private javax.swing.JTextArea txtSharerLog;
    private javax.swing.JTextArea txtSharerText;
    private javax.swing.JTextField txtStream;
    private javax.swing.JTextField txtToHour;
    private javax.swing.JTextField txtToMinute;
    private javax.swing.JTextField txtToSecond;
    private javax.swing.JTextArea txtUploaderDescription;
    private javax.swing.JTextArea txtUploaderLog;
    private javax.swing.JTextField txtUploaderTags;
    private javax.swing.JTextField txtUploaderTitle;
    // End of variables declaration//GEN-END:variables
}
